name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup user
        run: $GITHUB_WORKSPACE/.github/workflows/ci_user_setup.sh
      - name: setup
        run: su - tester -c "$GITHUB_WORKSPACE/setup.sh"
      
