name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: setup user
        run: |
          yum install -y shadow-utils sudo util-linux tar
          adduser tester
          echo "tester  ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/tester
          su - tester -c id
          su - tester -c "mkdir -p /home/tester/Downloads"
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          su - tester -c "$GITHUB_WORKSPACE/setup.sh"
      
